# Available ruby versions: http://rubies.travis-ci.org/

language: ruby

os:
  - linux
  - osx

rvm:
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2.5"
  - "2.3.3"
  - "2.4.0"
  - "ruby-head"
  - "jruby-9.0.5.0"
  - "jruby-9.1.5.0"
  - "jruby-head"

cache: bundler

script:
  bundle exec rake test

branches:
  except:
    - "readme-edits"

before_install:
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

# Travis OS X support is pretty janky. These are some hacks to include tests
# only on versions that actually work.
# (last tested: 2016-11)
matrix:
  # exclude: {}
  # include: {}

  allow_failures:
    - rvm: 'ruby-head'

  # return results as soon as mandatory versions are done
  fast_finish: true

sudo: false
