language: ruby
os:
  - linux
  - osx
rvm:
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2" # latest 2.2.x
  - "2.3.0" # latest 2.3.x
  - "jruby-9.0" # jruby 2.2.x
  - "jruby-head"
script:
  bundle exec rake test
branches:
  except:
    - "readme-edits"

# These versions do not yet work on OS X on Travis
# (last tested: 2015-09)
matrix:
  exclude:
    - os: osx
      rvm: '2.2'

sudo: false
